"""baseline

Revision ID: c7b889e962d2
Revises: 
Create Date: 2026-03-23 01:45:32.839664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b889e962d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('job_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('started_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('finished_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'running'"))
        batch_op.create_index(batch_op.f('ix_job_runs_job_name'), ['job_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_job_name'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'running'"))
        batch_op.alter_column('finished_at',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('job_name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
