"""
SQLAlchemy ORM models for all 6 SQLite tables.
Defined once here — every service imports from this module.
Schema changes here cascade to all services.
"""

import json
import struct
from datetime import datetime

from sqlalchemy import (
    Boolean, Column, DateTime, Float, ForeignKey,
    Integer, LargeBinary, String, Text, UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, relationship

# ── Embedding vector pack/unpack helpers ──────────────────────────────────────
# Store 3072-dim float32 vectors as 12 KB BLOB instead of ~25 KB JSON string.
_DIMS = 3072
_PACK_FMT = f"<{_DIMS}f"   # little-endian, 3072 × float32


def pack_vector(vector: list[float]) -> bytes:
    """Encode a list of 3072 floats → 12 288-byte BLOB."""
    return struct.pack(_PACK_FMT, *vector)


def unpack_vector(blob: bytes) -> list[float]:
    """Decode a 12 288-byte BLOB → list of 3072 floats."""
    return list(struct.unpack(_PACK_FMT, blob))


class Base(DeclarativeBase):
    pass


class RawIngestion(Base):
    """
    Raw data from all external sources before any processing.
    Unique constraint on (source, symbol, timestamp) ensures idempotent inserts.
    """
    __tablename__ = "raw_ingestion"
    __table_args__ = (
        UniqueConstraint("source", "symbol", "timestamp", name="uq_raw_source_symbol_ts"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    source = Column(String(64), nullable=False, index=True)       # fred, eia, newsdata, aishub, sentinel1, etc.
    commodity = Column(String(32), nullable=False, index=True)    # lng, copper, soybeans
    symbol = Column(String(64), nullable=False)                   # ticker/series/keyword
    timestamp = Column(DateTime, nullable=False, index=True)      # data timestamp (not ingest time)
    data_type = Column(String(32), nullable=False, index=True)    # price_historical, price_realtime, news, ais, satellite
    raw_json = Column(Text, nullable=False)                       # full API response as JSON string
    ingested_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    processed = Column(Boolean, nullable=False, default=False, index=True)


class ProcessedFeature(Base):
    """
    Derived features computed by the processor from raw_ingestion rows.
    One raw row can produce multiple feature rows (e.g., price + sentiment).
    """
    __tablename__ = "processed_features"

    id = Column(Integer, primary_key=True, autoincrement=True)
    raw_ingestion_id = Column(Integer, ForeignKey("raw_ingestion.id"), nullable=False, index=True)
    commodity = Column(String(32), nullable=False, index=True)
    feature_type = Column(String(64), nullable=False)             # sentiment_score, pct_change, log_return, vessel_count, backscatter_mean
    value = Column(Float, nullable=True)
    value_json = Column(Text, nullable=True)                      # for complex features (e.g., vessel positions)
    window = Column(String(32), nullable=True)                    # rolling window label: 1d, 7d, 30d
    computed_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    raw_ingestion = relationship("RawIngestion", backref="features")


class AnomalyEvent(Base):
    """
    Detected anomalies. The status field is the queue mechanism between
    the processor and the AI engine — no message broker needed.
    Status flow: new → embedding_queued → processed
    """
    __tablename__ = "anomaly_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    commodity = Column(String(32), nullable=False, index=True)
    anomaly_type = Column(String(64), nullable=False)             # price_spike, sentiment_shift, ais_vessel_drop, ais_cluster, satellite_backscatter
    severity = Column(Float, nullable=False)                      # Z-score magnitude or normalised score
    detected_at = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)
    source_ids = Column(Text, nullable=False)                     # JSON array of raw_ingestion.id values
    status = Column(String(32), nullable=False, default="new", index=True)  # new | embedding_queued | processed
    metadata_json = Column(Text, nullable=True)                   # extra context: window, threshold, symbol

    @property
    def source_id_list(self) -> list[int]:
        return json.loads(self.source_ids)


class EmbeddingCache(Base):
    """
    Stores embedding vectors generated by Gemini for each anomaly event.
    Qdrant holds the live searchable copy; this is the SQLite audit record.

    Storage efficiency (H2):
      vector_blob  — compact binary (3072 × float32 = 12 KB) — preferred for new rows
      vector_json  — legacy JSON text (~25 KB) — kept for backwards compatibility;
                     will be NULL for rows created after the H2 migration.

    Use pack_vector() / unpack_vector() from shared.models to convert.
    """
    __tablename__ = "embeddings_cache"

    id = Column(Integer, primary_key=True, autoincrement=True)
    anomaly_event_id = Column(Integer, ForeignKey("anomaly_events.id"), nullable=False, unique=True, index=True)
    model = Column(String(64), nullable=False, default="text-embedding-004")
    vector_blob = Column(LargeBinary, nullable=True)              # compact binary: 3072 × float32 = 12 KB
    vector_json = Column(Text, nullable=True)                     # legacy JSON fallback (~25 KB)
    context_payload = Column(Text, nullable=True)                 # the text/context sent to Gemini
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    anomaly_event = relationship("AnomalyEvent", backref="embedding")

    def get_vector(self) -> list[float] | None:
        """Return the embedding vector, preferring the compact BLOB format."""
        if self.vector_blob:
            return unpack_vector(self.vector_blob)
        if self.vector_json:
            return json.loads(self.vector_json)
        return None


class SignalAlert(Base):
    """
    Correlation results: new anomaly matched against historical embeddings in Qdrant.
    Tracks price outcomes over 1w/2w/1m monitoring windows.
    """
    __tablename__ = "signal_alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    anomaly_event_id = Column(Integer, ForeignKey("anomaly_events.id"), nullable=False, index=True)
    commodity = Column(String(32), nullable=False, index=True)
    alert_type = Column(String(64), nullable=False)               # similar_historical, novel_event
    correlated_anomaly_ids = Column(Text, nullable=False)         # JSON array of anomaly_event.id
    similarity_scores = Column(Text, nullable=False)              # JSON array of floats (parallel to above)
    price_at_alert = Column(Float, nullable=True)
    price_1w = Column(Float, nullable=True)
    price_2w = Column(Float, nullable=True)
    price_1m = Column(Float, nullable=True)
    monitoring_complete = Column(Boolean, nullable=False, default=False, index=True)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    # Pre-event prediction fields (added for prediction engine)
    prediction_json = Column(Text, nullable=True)                 # full prediction JSON string
    prediction_type = Column(String(32), nullable=True)           # directional|magnitude_only|no_signal
    prediction_confidence = Column(Float, nullable=True)          # 0.0-1.0

    anomaly_event = relationship("AnomalyEvent", backref="alerts")


class CausalityReport(Base):
    """
    Post-event causal analysis generated by Gemini after monitoring window closes.
    """
    __tablename__ = "causality_reports"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_alert_id = Column(Integer, ForeignKey("signal_alerts.id"), nullable=False, unique=True, index=True)
    commodity = Column(String(32), nullable=False, index=True)
    report_json = Column(Text, nullable=False)                    # full Gemini response JSON
    cause_category = Column(String(128), nullable=True)           # extracted top-level cause
    confidence_score = Column(Float, nullable=True)               # 0.0–1.0
    price_impact_pct = Column(Float, nullable=True)               # actual price change %
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    signal_alert = relationship("SignalAlert", backref="report")


class PredictionEvaluation(Base):
    """
    Post-event evaluation comparing pre-event prediction against actual outcomes.
    Created after a CausalityReport exists for the linked SignalAlert.
    """
    __tablename__ = "prediction_evaluations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_alert_id = Column(Integer, ForeignKey("signal_alerts.id"), nullable=False, unique=True, index=True)
    commodity = Column(String(32), nullable=False, index=True)
    actual_price_change_pct = Column(Float, nullable=True)
    prediction_accuracy_json = Column(Text, nullable=True)        # {direction_correct, magnitude_error, volatility_correct, confidence_validity}
    causal_analysis_json = Column(Text, nullable=True)            # {correct_drivers, missed_drivers, overestimated_drivers}
    failure_modes_json = Column(Text, nullable=True)              # JSON array of strings
    learning_update_json = Column(Text, nullable=True)            # {insight, future_adjustment, affected_signal_types}
    overall_score = Column(Float, nullable=True)                  # 0.0-1.0 composite
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    signal_alert = relationship("SignalAlert", backref="evaluation")


class LearningUpdate(Base):
    """
    Extracted learning insights from prediction evaluations for future signal interpretation.
    """
    __tablename__ = "learning_updates"

    id = Column(Integer, primary_key=True, autoincrement=True)
    prediction_evaluation_id = Column(Integer, ForeignKey("prediction_evaluations.id"), nullable=False, index=True)
    commodity = Column(String(32), nullable=False, index=True)
    anomaly_type = Column(String(64), nullable=True)
    insight = Column(Text, nullable=True)
    future_adjustment = Column(Text, nullable=True)
    affected_signal_types = Column(Text, nullable=True)           # JSON array
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    evaluation = relationship("PredictionEvaluation", backref="learning_updates")


class JobRun(Base):
    """
    Scheduler job run history — one row per job execution.
    Written by scheduler/job_history.py; read by the /health endpoint.
    """
    __tablename__ = "job_runs"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    job_name    = Column(String(64), nullable=False, index=True)
    started_at  = Column(String(32), nullable=False)
    finished_at = Column(String(32), nullable=True)
    status      = Column(String(16), nullable=False, default="running")
    error       = Column(Text, nullable=True)
    summary_json = Column(Text, nullable=True)
