"""
Backtest page — walk-forward prediction evaluation on historical disruptions.

Reads reports/backtest_report.json (generated by scripts/backtest_engine.py)
and displays regime-level summary + per-event results.
"""

import json
from pathlib import Path

import pandas as pd
import streamlit as st

# Project root is three levels up: dashboard/views/ -> dashboard/ -> project/
_REPORT_PATH = Path(__file__).parent.parent.parent / "reports" / "backtest_report.json"

DIRECTION_ICONS = {True: "OK", False: "X", None: "—"}
REGIME_ORDER = ["normal", "stress", "crisis", "black_swan", "ALL"]


def _fmt_pct(val) -> str:
    if val is None:
        return "N/A"
    return f"{val * 100:.1f}%"


def _fmt_float(val, decimals=3) -> str:
    if val is None:
        return "N/A"
    return f"{val:.{decimals}f}"


def _fmt_signed_pct(val) -> str:
    if val is None:
        return "N/A"
    return f"{val:+.1f}%"


def render():
    st.subheader("Backtesting Engine")

    if not _REPORT_PATH.exists():
        st.info(
            "No backtest report found.\n\n"
            "Generate one with:\n"
            "```\n"
            "# Dry run (no API calls — exercises scoring only)\n"
            "python -m scripts.backtest_engine --dry-run\n\n"
            "# Live run with walk-forward feedback (uses Gemini)\n"
            "python -m scripts.backtest_engine --feedback\n"
            "```"
        )
        return

    with open(_REPORT_PATH) as f:
        report = json.load(f)

    config = report.get("config", {})
    regime_summary = report.get("regime_summary", [])
    per_event = report.get("per_event_results", [])
    generated_at = report.get("generated_at", "")[:19]

    # ── Config banner ─────────────────────────────────────────────────────────
    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Events (Test)", config.get("n_test_events", len(per_event)))
    col2.metric("Events (Train)", config.get("n_train_events", 0))
    col3.metric("Train Cutoff", str(config.get("train_cutoff", "—"))[:10])
    col4.metric("Feedback Mode", "On" if config.get("feedback_mode") else "Off")
    col5.metric("Dry Run", "Yes" if config.get("dry_run") else "No")

    # ── Contamination warning ─────────────────────────────────────────────────
    with st.expander("LLM contamination note (read before interpreting results)"):
        st.warning(report.get("contamination_note", ""))

    st.markdown("---")

    # ── Regime summary ────────────────────────────────────────────────────────
    st.markdown("#### Regime Summary")

    rows = []
    for regime in REGIME_ORDER:
        m = next((r for r in regime_summary if r["regime"] == regime), None)
        if m is None:
            continue
        rows.append({
            "Regime": m["regime"],
            "N Events": m["n_events"],
            "Dir Accuracy": _fmt_pct(m.get("direction_accuracy")),
            "Mean MAE (pp)": _fmt_float(m.get("mean_magnitude_mae_pp"), 2),
            "Mean Brier": _fmt_float(m.get("mean_brier_score"), 3),
            "Composite": _fmt_float(m.get("mean_composite_score"), 3),
            "No-Signal %": _fmt_pct(m.get("no_signal_rate")),
        })

    if rows:
        df = pd.DataFrame(rows)
        # Bold the ALL row by placing it at the end naturally (already last in REGIME_ORDER)
        st.dataframe(df, use_container_width=True, hide_index=True)
    else:
        st.info("No regime data in report.")

    st.markdown("---")

    # ── Per-event results ─────────────────────────────────────────────────────
    st.markdown("#### Per-Event Results (Test Set)")

    if not per_event:
        st.info("No per-event results.")
    else:
        event_rows = []
        for r in per_event:
            dc = r.get("direction_correct")
            event_rows.append({
                "Event ID": r.get("event_id", ""),
                "Commodity": (r.get("commodity") or "").upper(),
                "Regime": r.get("regime", ""),
                "Direction": DIRECTION_ICONS.get(dc, "—"),
                "Actual %": _fmt_signed_pct(r.get("actual_pct_1m")),
                "Predicted %": _fmt_signed_pct(r.get("predicted_pct_midpoint")),
                "MAE (pp)": _fmt_float(r.get("magnitude_mae"), 2),
                "Brier": _fmt_float(r.get("brier_score"), 3),
                "Composite": _fmt_float(r.get("composite_score"), 3),
                "Pred Type": r.get("prediction_type", ""),
                "As-of Date": (r.get("as_of_date") or "")[:10],
            })

        # Commodity filter
        commodities = sorted({r["Commodity"] for r in event_rows})
        selected = st.multiselect(
            "Filter by commodity",
            options=commodities,
            default=commodities,
            key="backtest_commodity_filter",
        )
        filtered = [r for r in event_rows if r["Commodity"] in selected]

        st.dataframe(pd.DataFrame(filtered), use_container_width=True, hide_index=True)

        # Quick stats below table
        total = len(filtered)
        directional = [r for r in filtered if r["Pred Type"] == "directional"]
        correct = [r for r in directional if r["Direction"] == "OK"]
        dir_acc = len(correct) / len(directional) * 100 if directional else None

        sc1, sc2, sc3 = st.columns(3)
        sc1.metric("Events shown", total)
        sc2.metric("Directional", len(directional))
        sc3.metric("Direction Accuracy", f"{dir_acc:.1f}%" if dir_acc is not None else "N/A")

    # ── Footer ────────────────────────────────────────────────────────────────
    st.markdown("---")
    st.caption(
        f"Report generated: {generated_at} UTC  |  "
        f"Path: `{_REPORT_PATH}`  |  "
        f"Re-run: `python -m scripts.backtest_engine --feedback`"
    )
